name: Feature request
description: Missing functionality
title: "[REQUEST] <title>"
labels: ['enhancement']
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What is the feature you want to see?
    validations:
      required: true